import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {Miniflare,convertV4MiniflareOptions} from 'miniflare';import {registerProfile,profileEnv,publicProfiles} from '../src/profiles';import {seal,digest} from '../src/core';import {now,type AppEnv,account} from '../src/meta';import worker from '../src/index';
test('multiple profiles preserve primary data and isolate settings, rules and disconnect',async()=>{
 const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:'2026-09-15',d1Databases:['DB'],bindings:{APP_KEY:'test',ADMIN_PASSWORD:'test',GRAPH_VERSION:'v25.0',LICENSE_SERVER_URL:'https://license.example'}}));
 try{const root=await mf.getBindings<AppEnv>();for(const file of ['0001_initial.sql','0002_conversations.sql'])for(const sql of readFileSync('migrations/'+file,'utf8').split(';').map(x=>x.trim()).filter(Boolean))await root.DB.prepare(sql).run();
 const first={id:'111111',username:'first',token:await seal('token1',root.APP_KEY),expires:now()+86400,refreshed:now()};await root.DB.prepare('INSERT INTO account VALUES(?,?,?,?,?)').bind(first.id,first.username,first.token,first.expires,first.refreshed).run();
 for(const sql of readFileSync('migrations/0003_profiles.sql','utf8').split(';').map(x=>x.trim()).filter(Boolean))await root.DB.prepare(sql).run();
 await root.DB.prepare("INSERT INTO settings VALUES('meta',?)").bind(await seal(JSON.stringify({appId:'123456',appSecret:'secret',owner:'Test',contact:'test@example.com',verifyToken:'verify'}),root.APP_KEY)).run();
 const second={...first,id:'222222',username:'second',token:await seal('token2',root.APP_KEY)};const other=await registerProfile(root,second);await other.DB.prepare('INSERT INTO account VALUES(?,?,?,?,?)').bind(second.id,second.username,second.token,second.expires,second.refreshed).run();
 for(const [env,name] of [[root,'A'],[other,'B']] as const)await env.DB.prepare('INSERT INTO rules(id,name,trigger,keywords,message,link,active,created) VALUES(?,?,?,?,?,?,?,?)').bind('same',name,'dm','quero',name,'https://example.com',1,now()).run();
 assert.equal((await account(await profileEnv(root,'222222')))?.username,'second');assert.equal((await publicProfiles(root)).length,2);assert.equal((await root.DB.prepare('SELECT name FROM rules').first<any>()).name,'A');assert.equal((await other.DB.prepare('SELECT name FROM rules').first<any>()).name,'B');
 await other.DB.prepare("INSERT INTO settings VALUES('license-cache','second-only')").run();assert.equal(await root.DB.prepare("SELECT value FROM settings WHERE key='license-cache'").first(),null);
 await root.DB.prepare('INSERT INTO sessions VALUES(?,?)').bind(await digest('demo-session'),now()+1000).run();const headers={Cookie:'dc_session=demo-session; dc_profile=222222',Origin:'https://test.example'};const ctx={waitUntil(){},passThroughOnException(){},props:{},exports:{}} as unknown as ExecutionContext;
 const status=await worker.fetch(new Request('https://test.example/api/status',{headers}),root,ctx);assert.equal(status.status,200);const state=await status.json() as any;assert.equal(state.account.id,'222222');assert.equal(state.license.paused,true);assert.equal(JSON.stringify(state).includes('token2'),false);
 const disconnected=await worker.fetch(new Request('https://test.example/api/disconnect',{method:'POST',headers}),root,ctx);assert.equal(disconnected.status,200);assert.equal(await account(other),null);assert.equal((await account(root))?.id,'111111');assert.equal((await root.DB.prepare('SELECT active FROM rules').first<any>()).active,1);
 }finally{await mf.dispose();}
});
