CREATE TABLE IF NOT EXISTS profiles (id TEXT PRIMARY KEY, prefix TEXT NOT NULL UNIQUE);
INSERT OR IGNORE INTO profiles(id,prefix) SELECT id,'' FROM account LIMIT 1;
ALTER TABLE oauth ADD COLUMN profile_id TEXT NOT NULL DEFAULT '';
ALTER TABLE oauth ADD COLUMN add_account INTEGER NOT NULL DEFAULT 0;
